version: '3'
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - nombresapi

  api:
    container_name: api
    image: node:latest
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
    networks:
      - nombresapi

  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - nombresapi

volumes:
  mongo-data:

networks:
  nombresapi:
    driver: bridge